name: "Test: Get Plugin Meta"
permissions:
  contents: read
on:
  workflow_dispatch:

jobs:
  test:
    uses: krokedil/krokedil-wp-ci/.github/workflows/get-plugin-meta.yml@develop-tests
    with:
      use_fixture_plugin: true
