name: "Test: Create Plugin Dev Zip"
permissions:
  contents: read
on:
  workflow_dispatch:
    inputs:
      test_php_versions:
        required: false
        type: string
        default: "8.3"
        description: "PHP versions used for basic testing of the plugin dev zip: 8.4,8.3,8.2,8.1,8.0,7.4 (comma-separated) or 'all'."

jobs:
  test:
    uses: krokedil/krokedil-wp-ci/.github/workflows/create-plugin-dev-zip.yml@develop-tests
    with:
      aws_upload: true
      use_fixture_plugin: true
      test_php_versions: ${{ inputs.test_php_versions }}
    secrets:
      AWS_ACCESS_KEY_ID_KROKEDIL_PLUGIN_DEV_ZIP: ${{ secrets.AWS_ACCESS_KEY_ID_KROKEDIL_PLUGIN_DEV_ZIP }}
      AWS_SECRET_ACCESS_KEY_KROKEDIL_PLUGIN_DEV_ZIP: ${{ secrets.AWS_SECRET_ACCESS_KEY_KROKEDIL_PLUGIN_DEV_ZIP }}
      SLACK_WEBHOOK_URL_KROKEDIL_E2E_NOTIFICATIONS: ${{ secrets.SLACK_WEBHOOK_URL_KROKEDIL_E2E_NOTIFICATIONS }}
